### ISSUE TITLE
edkrepo status and combo command visual update

### ISSUE THREAD

**Issue by ndhaller** [tianocore/edk2-edkrepo#181]
Recently updated "edkrepo list-repos" command displays:
-default combo names are in green text
-the localRoot name in purple text
-includes the Remote URL of the localRoot in red text
-tags and branch names are in dark blue text.

Recently updated "edkrepo combo -v" command displays:
-current combo name in green text
-the localRoot name in white text
-tag and branch names in white txt

"edkrepo status" command displays:
-Current combo in white text.
-the localRoot names in white text.
-branch , tag , commit status in white text.
-no Remote URL information for each localRoot

Feature request is to use some of the color identifiers from the global list-repos command in the local combo and status commands.
-current combo name in green text
-the localRoot name in purple text
-branch, tag, commit names in dark blue text

Separately, is there a local project edkrepo command like 'edkrepo status' that can shortcut display the Remote URL for each localRoot, without having to open the repo/Manifest.xml file or run individual 'git remote -v' commands?
```[tasklist]
### Tasks
- [ ] https://github.com/tianocore/edk2-edkrepo/issues/202
- [ ] https://github.com/tianocore/edk2-edkrepo/issues/203
- [ ] https://github.com/tianocore/edk2-edkrepo/issues/204
```

**Comment by ndhaller** [comment]
I think edkrepo v3.2.2 release covered all of these initial change requests.
